# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\OscilloscopeCollection\mainWindow.ui'
#
# Created: Wed Mar 18 17:16:52 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbSettingsCH1 = QtGui.QGroupBox(self.tab)
        self.cbSettingsCH1.setFlat(True)
        self.cbSettingsCH1.setCheckable(True)
        self.cbSettingsCH1.setObjectName(_fromUtf8("cbSettingsCH1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.cbSettingsCH1)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tSettingsCH1 = QtGui.QLineEdit(self.cbSettingsCH1)
        self.tSettingsCH1.setObjectName(_fromUtf8("tSettingsCH1"))
        self.horizontalLayout_3.addWidget(self.tSettingsCH1)
        self.horizontalLayout.addWidget(self.cbSettingsCH1)
        self.cbSettingsCH2 = QtGui.QGroupBox(self.tab)
        self.cbSettingsCH2.setFlat(True)
        self.cbSettingsCH2.setCheckable(True)
        self.cbSettingsCH2.setChecked(False)
        self.cbSettingsCH2.setObjectName(_fromUtf8("cbSettingsCH2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.cbSettingsCH2)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tSettingsCH2 = QtGui.QLineEdit(self.cbSettingsCH2)
        self.tSettingsCH2.setObjectName(_fromUtf8("tSettingsCH2"))
        self.horizontalLayout_4.addWidget(self.tSettingsCH2)
        self.horizontalLayout.addWidget(self.cbSettingsCH2)
        self.cbSettingsCH3 = QtGui.QGroupBox(self.tab)
        self.cbSettingsCH3.setFlat(True)
        self.cbSettingsCH3.setCheckable(True)
        self.cbSettingsCH3.setChecked(False)
        self.cbSettingsCH3.setObjectName(_fromUtf8("cbSettingsCH3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.cbSettingsCH3)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tSettingsCH3 = QtGui.QLineEdit(self.cbSettingsCH3)
        self.tSettingsCH3.setObjectName(_fromUtf8("tSettingsCH3"))
        self.horizontalLayout_6.addWidget(self.tSettingsCH3)
        self.horizontalLayout.addWidget(self.cbSettingsCH3)
        self.cbSettingsCH4 = QtGui.QGroupBox(self.tab)
        self.cbSettingsCH4.setFlat(True)
        self.cbSettingsCH4.setCheckable(True)
        self.cbSettingsCH4.setChecked(False)
        self.cbSettingsCH4.setObjectName(_fromUtf8("cbSettingsCH4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.cbSettingsCH4)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tSettingsCH4 = QtGui.QLineEdit(self.cbSettingsCH4)
        self.tSettingsCH4.setObjectName(_fromUtf8("tSettingsCH4"))
        self.horizontalLayout_5.addWidget(self.tSettingsCH4)
        self.horizontalLayout.addWidget(self.cbSettingsCH4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tSaveComments = QtGui.QPlainTextEdit(self.groupBox_3)
        self.tSaveComments.setObjectName(_fromUtf8("tSaveComments"))
        self.horizontalLayout_9.addWidget(self.tSaveComments)
        self.horizontalLayout_13.addWidget(self.groupBox_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cbSettingsAve = QtGui.QGroupBox(self.tab)
        self.cbSettingsAve.setFlat(True)
        self.cbSettingsAve.setCheckable(True)
        self.cbSettingsAve.setChecked(False)
        self.cbSettingsAve.setObjectName(_fromUtf8("cbSettingsAve"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.cbSettingsAve)
        self.horizontalLayout_7.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tSettingsAve = QINumberEdit(self.cbSettingsAve)
        self.tSettingsAve.setObjectName(_fromUtf8("tSettingsAve"))
        self.horizontalLayout_7.addWidget(self.tSettingsAve)
        self.verticalLayout_5.addWidget(self.cbSettingsAve)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tSettingsSaveName = QtGui.QLineEdit(self.groupBox_2)
        self.tSettingsSaveName.setObjectName(_fromUtf8("tSettingsSaveName"))
        self.horizontalLayout_8.addWidget(self.tSettingsSaveName)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cSettingsGPIB = QtGui.QComboBox(self.groupBox)
        self.cSettingsGPIB.setObjectName(_fromUtf8("cSettingsGPIB"))
        self.horizontalLayout_2.addWidget(self.cSettingsGPIB)
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.horizontalLayout_13.setStretch(0, 9)
        self.horizontalLayout_13.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.tSettingsSaveDir = QtGui.QLineEdit(self.groupBox_4)
        self.tSettingsSaveDir.setEnabled(False)
        self.tSettingsSaveDir.setObjectName(_fromUtf8("tSettingsSaveDir"))
        self.horizontalLayout_11.addWidget(self.tSettingsSaveDir)
        self.bSettingsChooseDir = QtGui.QPushButton(self.groupBox_4)
        self.bSettingsChooseDir.setObjectName(_fromUtf8("bSettingsChooseDir"))
        self.horizontalLayout_11.addWidget(self.bSettingsChooseDir)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hlChannels = QtGui.QHBoxLayout()
        self.hlChannels.setObjectName(_fromUtf8("hlChannels"))
        self.verticalLayout.addLayout(self.hlChannels)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.bCHPause = QtGui.QPushButton(self.tab_2)
        self.bCHPause.setCheckable(True)
        self.bCHPause.setChecked(True)
        self.bCHPause.setObjectName(_fromUtf8("bCHPause"))
        self.gridLayout_2.addWidget(self.bCHPause, 2, 1, 1, 1)
        self.bCHSave = QButtonDblClick(self.tab_2)
        self.bCHSave.setCheckable(True)
        self.bCHSave.setObjectName(_fromUtf8("bCHSave"))
        self.gridLayout_2.addWidget(self.bCHSave, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.setStretch(0, 1000)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gBoxcar = PlotWidget(self.tab_3)
        self.gBoxcar.setObjectName(_fromUtf8("gBoxcar"))
        self.verticalLayout_3.addWidget(self.gBoxcar)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.cBoxcarCHX = QtGui.QComboBox(self.tab_3)
        self.cBoxcarCHX.setObjectName(_fromUtf8("cBoxcarCHX"))
        self.horizontalLayout_10.addWidget(self.cBoxcarCHX)
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        self.cBoxcarCHY = QtGui.QComboBox(self.tab_3)
        self.cBoxcarCHY.setObjectName(_fromUtf8("cBoxcarCHY"))
        self.horizontalLayout_10.addWidget(self.cBoxcarCHY)
        self.horizontalLayout_10.setStretch(0, 10)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.setStretch(2, 10)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bBoxcarPopout = QtGui.QPushButton(self.tab_3)
        self.bBoxcarPopout.setObjectName(_fromUtf8("bBoxcarPopout"))
        self.gridLayout.addWidget(self.bBoxcarPopout, 0, 0, 1, 1)
        self.bBoxcarCollect = QtGui.QPushButton(self.tab_3)
        self.bBoxcarCollect.setCheckable(True)
        self.bBoxcarCollect.setObjectName(_fromUtf8("bBoxcarCollect"))
        self.gridLayout.addWidget(self.bBoxcarCollect, 0, 1, 1, 1)
        self.bBoxcarSave = QtGui.QPushButton(self.tab_3)
        self.bBoxcarSave.setObjectName(_fromUtf8("bBoxcarSave"))
        self.gridLayout.addWidget(self.bBoxcarSave, 1, 0, 1, 1)
        self.bBoxcarReset = QtGui.QPushButton(self.tab_3)
        self.bBoxcarReset.setObjectName(_fromUtf8("bBoxcarReset"))
        self.gridLayout.addWidget(self.bBoxcarReset, 1, 1, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.cbSettingsCH1.setTitle(_translate("MainWindow", "Channel 1", None))
        self.tSettingsCH1.setText(_translate("MainWindow", "CH1", None))
        self.cbSettingsCH2.setTitle(_translate("MainWindow", "Channel 2", None))
        self.tSettingsCH2.setText(_translate("MainWindow", "CH2", None))
        self.cbSettingsCH3.setTitle(_translate("MainWindow", "Channel 3", None))
        self.tSettingsCH3.setText(_translate("MainWindow", "CH3", None))
        self.cbSettingsCH4.setTitle(_translate("MainWindow", "Channel 4", None))
        self.tSettingsCH4.setText(_translate("MainWindow", "CH4", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Comments", None))
        self.cbSettingsAve.setTitle(_translate("MainWindow", "Average", None))
        self.tSettingsAve.setText(_translate("MainWindow", "1", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Base Save Name", None))
        self.groupBox.setTitle(_translate("MainWindow", "Scope GPIB", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Save Directory", None))
        self.bSettingsChooseDir.setText(_translate("MainWindow", "Choose", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings", None))
        self.bCHPause.setText(_translate("MainWindow", "Pause", None))
        self.bCHSave.setText(_translate("MainWindow", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Channels", None))
        self.label.setText(_translate("MainWindow", "vs.", None))
        self.bBoxcarPopout.setText(_translate("MainWindow", "Popout", None))
        self.bBoxcarCollect.setText(_translate("MainWindow", "Collect", None))
        self.bBoxcarSave.setText(_translate("MainWindow", "Save", None))
        self.bBoxcarReset.setText(_translate("MainWindow", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Boxcar", None))

from pyqtgraph import PlotWidget
from InstsAndQt.customQt import QButtonDblClick, QINumberEdit
