# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\OscilloscopeCollection\mainWindow.ui'
#
# Created: Wed Mar 18 09:14:13 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(60, 70, 89, 53))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cSettingsGPIB = QtGui.QComboBox(self.groupBox)
        self.cSettingsGPIB.setObjectName(_fromUtf8("cSettingsGPIB"))
        self.horizontalLayout_2.addWidget(self.cSettingsGPIB)
        self.cbSettingsCH1 = QtGui.QGroupBox(self.tab)
        self.cbSettingsCH1.setGeometry(QtCore.QRect(280, 90, 153, 53))
        self.cbSettingsCH1.setFlat(True)
        self.cbSettingsCH1.setCheckable(True)
        self.cbSettingsCH1.setObjectName(_fromUtf8("cbSettingsCH1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.cbSettingsCH1)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tSettingsCH1 = QtGui.QLineEdit(self.cbSettingsCH1)
        self.tSettingsCH1.setObjectName(_fromUtf8("tSettingsCH1"))
        self.horizontalLayout_3.addWidget(self.tSettingsCH1)
        self.cbSettingsCH2 = QtGui.QGroupBox(self.tab)
        self.cbSettingsCH2.setGeometry(QtCore.QRect(440, 90, 153, 53))
        self.cbSettingsCH2.setFlat(True)
        self.cbSettingsCH2.setCheckable(True)
        self.cbSettingsCH2.setChecked(False)
        self.cbSettingsCH2.setObjectName(_fromUtf8("cbSettingsCH2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.cbSettingsCH2)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tSettingsCH2 = QtGui.QLineEdit(self.cbSettingsCH2)
        self.tSettingsCH2.setObjectName(_fromUtf8("tSettingsCH2"))
        self.horizontalLayout_4.addWidget(self.tSettingsCH2)
        self.cbSettingsCH3 = QtGui.QGroupBox(self.tab)
        self.cbSettingsCH3.setGeometry(QtCore.QRect(290, 170, 153, 53))
        self.cbSettingsCH3.setFlat(True)
        self.cbSettingsCH3.setCheckable(True)
        self.cbSettingsCH3.setChecked(False)
        self.cbSettingsCH3.setObjectName(_fromUtf8("cbSettingsCH3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.cbSettingsCH3)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tSettingsCH3 = QtGui.QLineEdit(self.cbSettingsCH3)
        self.tSettingsCH3.setObjectName(_fromUtf8("tSettingsCH3"))
        self.horizontalLayout_6.addWidget(self.tSettingsCH3)
        self.cbSettingsCH4 = QtGui.QGroupBox(self.tab)
        self.cbSettingsCH4.setGeometry(QtCore.QRect(460, 170, 153, 53))
        self.cbSettingsCH4.setFlat(True)
        self.cbSettingsCH4.setCheckable(True)
        self.cbSettingsCH4.setChecked(False)
        self.cbSettingsCH4.setObjectName(_fromUtf8("cbSettingsCH4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.cbSettingsCH4)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tSettingsCH4 = QtGui.QLineEdit(self.cbSettingsCH4)
        self.tSettingsCH4.setObjectName(_fromUtf8("tSettingsCH4"))
        self.horizontalLayout_5.addWidget(self.tSettingsCH4)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 290, 153, 53))
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.cbSettingsAve = QtGui.QGroupBox(self.tab)
        self.cbSettingsAve.setGeometry(QtCore.QRect(60, 230, 153, 53))
        self.cbSettingsAve.setFlat(True)
        self.cbSettingsAve.setCheckable(True)
        self.cbSettingsAve.setChecked(False)
        self.cbSettingsAve.setObjectName(_fromUtf8("cbSettingsAve"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.cbSettingsAve)
        self.horizontalLayout_7.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tSettingsAve = QINumberEdit(self.cbSettingsAve)
        self.tSettingsAve.setObjectName(_fromUtf8("tSettingsAve"))
        self.horizontalLayout_7.addWidget(self.tSettingsAve)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 240, 276, 225))
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout_9.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 50, 471, 181))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.hlChannels = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.hlChannels.setMargin(0)
        self.hlChannels.setObjectName(_fromUtf8("hlChannels"))
        self.bCHSave = QButtonDblClick(self.tab_2)
        self.bCHSave.setGeometry(QtCore.QRect(610, 430, 75, 23))
        self.bCHSave.setObjectName(_fromUtf8("bCHSave"))
        self.bCHPause = QtGui.QPushButton(self.tab_2)
        self.bCHPause.setGeometry(QtCore.QRect(470, 440, 75, 23))
        self.bCHPause.setObjectName(_fromUtf8("bCHPause"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.graphicsView = QtGui.QGraphicsView(self.tab_3)
        self.graphicsView.setGeometry(QtCore.QRect(210, 60, 256, 192))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 420, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 460, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 420, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Scope GPIB", None))
        self.cbSettingsCH1.setTitle(_translate("MainWindow", "Channel 1", None))
        self.tSettingsCH1.setText(_translate("MainWindow", "CH1", None))
        self.cbSettingsCH2.setTitle(_translate("MainWindow", "Channel 2", None))
        self.tSettingsCH2.setText(_translate("MainWindow", "CH2", None))
        self.cbSettingsCH3.setTitle(_translate("MainWindow", "Channel 3", None))
        self.tSettingsCH3.setText(_translate("MainWindow", "CH3", None))
        self.cbSettingsCH4.setTitle(_translate("MainWindow", "Channel 4", None))
        self.tSettingsCH4.setText(_translate("MainWindow", "CH4", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Base Save Name", None))
        self.cbSettingsAve.setTitle(_translate("MainWindow", "Average", None))
        self.tSettingsAve.setText(_translate("MainWindow", "1", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Comments", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings", None))
        self.bCHSave.setText(_translate("MainWindow", "Save", None))
        self.bCHPause.setText(_translate("MainWindow", "Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Channels", None))
        self.pushButton_2.setText(_translate("MainWindow", "Popout", None))
        self.pushButton_3.setText(_translate("MainWindow", "Save", None))
        self.pushButton_4.setText(_translate("MainWindow", "Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Boxcar", None))

from InstsAndQt.customQt import QButtonDblClick, QINumberEdit
